name: Build USB-Botbase (Docker)

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: devkitpro/devkita64:latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Build
        run: make -j

      - name: Show build tree (debug)
        run: |
          pwd
          ls -la
          # 看看是否真的生成了 atmosphere/ 或 out/、build/
          find . -maxdepth 3 -type d -name atmosphere -print -exec ls -la {} \;

      # 如果存在 atmosphere/ 就上传
      - name: Upload atmosphere (if exists)
        uses: actions/upload-artifact@v4
        with:
          name: usb-botbase-atmosphere
          path: atmosphere/**
          if-no-files-found: ignore

      # 可选兜底：把 out/ 和 build/ 也传上来
      - name: Upload out (if exists)
        uses: actions/upload-artifact@v4
        with:
          name: usb-botbase-out
          path: out/**
          if-no-files-found: ignore

      - name: Upload build (if exists)
        uses: actions/upload-artifact@v4
        with:
          name: usb-botbase-build
          path: build/**
          if-no-files-found: ignore
