name: Build USB-Botbase (Docker)

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: devkitpro/devkita64:latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Build
        run: make -j

      - name: Pack artifacts
        run: |
          mkdir -p dist
          # 如果项目编译直接产出 atmosphere/ 目录，就把它打包
          if [ -d atmosphere ]; then zip -r dist/USB-Botbase.zip atmosphere; fi
          # 也把 build/out 兜底带上（视你的项目产物而定）
          [ -d out ] && zip -r dist/out.zip out || true
          [ -d build ] && zip -r dist/build.zip build || true

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: usb-botbase-artifacts
          path: dist/*.zip
